---
- name: "Deploy script"
  copy:
    content: |
        #!/bin/bash
        cd {{ galaxy_root }};
        for dir in {custom-tools,dynamic_rules,interactive_environments,mutable-config,mutable-data,server,venv,venv3,tool-data}; do
            if [ -d $dir ]; then
                echo "Syncing $dir"
                rsync -avr --delete --exclude client/node_modules $dir/ {{ galaxy_nfs_location }}/$dir/
            else
                echo "Skipping $dir"
            fi
        done;
        if [ -d shed_tools-local ]; then
            echo "Syncing shed_tools-local"
            rsync -avr --delete shed_tools-local/ {{ galaxy_nfs_location }}/shed_tools/
        else
            echo "Skipping shed_tools-local"
        fi
    dest: /usr/bin/galaxy-sync-to-nfs
    owner: root
    group: root
    mode: 0755

#- name: Add to cron
  #cron:
    #name: "Fix unscheduled jobs"
    #minute: "*/20"
    #job: /usr/bin/galaxy-fix-unscheduled-jobs
    #user: "{{ galaxy_user.name }}"
